---
# Source: jenkins/templates/jenkins-agent-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-jenkins-agent
  labels:
    app: my-jenkins
    chart: "jenkins-0.28.8"
    component: "my-jenkins-jenkins-master"
spec:
  ports:
    - port: 50000
      targetPort: 50000
      
      name: slavelistener
  selector:
    component: "my-jenkins-jenkins-master"
  type: ClusterIP
