---
# Source: jenkins/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: my-jenkins
  labels:
    app: my-jenkins
    chart: "jenkins-0.28.8"
    release: "my-jenkins"
    heritage: "Tiller"
type: Opaque
data:
  
  jenkins-admin-password: "RnlpYUpSNm0zMQ=="
  
  jenkins-admin-user: "YWRtaW4="