---
# Source: jenkins/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-jenkins
  labels:
    app: my-jenkins
    chart: "jenkins-0.28.8"
    release: "my-jenkins"
    heritage: "Tiller"
