---
# Source: prometheus/templates/kube-state-metrics-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus
    chart: prometheus-5.5.3
    component: "kube-state-metrics"
    heritage: Tiller
    release: release-name
  name: release-name-prometheus-kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: release-name-prometheus-kube-state-metrics
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-prometheus-kube-state-metrics
