---
# Source: prometheus/templates/node-exporter-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus
    chart: prometheus-5.5.3
    component: "node-exporter"
    heritage: Tiller
    release: release-name
  name: release-name-prometheus-node-exporter
subjects:
  - kind: ServiceAccount
    name: release-name-prometheus-node-exporter
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
