---
# Source: prometheus/templates/node-exporter-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-5.5.3
    component: "node-exporter"
    heritage: Tiller
    release: release-name
  name: release-name-prometheus-node-exporter
