---
# Source: prometheus/templates/server-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-5.5.3
    component: "server"
    heritage: Tiller
    release: release-name
  name: release-name-prometheus-server
