---
# Source: nginx-ingress/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.1.4
    component: "controller"
    heritage: Tiller
    release: my-nginx
  name: my-nginx-nginx-ingress-controller
data:
  enable-vts-status: "false"
