---
# Source: nginx-ingress/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.1.4
    heritage: Tiller
    release: my-nginx
  name: my-nginx-nginx-ingress